nodes = ["discovery:7171"]
    enableprotect = false

[env]
    region = "sh"
    zone = "sh001"
    host = "discovery"
    DeployEnv = "dev"

[httpServer]
    addr = "discovery:7171"
    timeout = "40s"

[httpClient]
    dial = "1s"
    keepAlive = "120s"
    timeout = "40s"

[log]
    stdout = true
