# This is a TOML document. Boom
MQType = "nats"

[discovery]
    nodes = ["127.0.0.1:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]

[Nats]
    Subject = "goim-push"
    Addr = "nats://localhost:4222"
